services:
  djangoapp:
    container_name: blog_django_form_app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - blog_django_form_db
  blog_django_form_db:
    container_name: blog_django_form_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=blog_django_form_db
      - POSTGRES_USER=blog_form_user
      - POSTGRES_PASSWORD=blog_form_password_2024
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
