# Generated by Django 4.2.21 on 2025-05-22 21:38

from django.db import migrations, models
import utils.models_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='assets/favicon/%Y/%m/%d', validators=[utils.models_validators.validate_png]),
        ),
    ]
