# Generated by Django 4.2.23 on 2025-07-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marque para exibir a página publicamente'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_in_post_content',
            field=models.BooleanField(default=True, help_text='Exibir a capa dentro do post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(help_text='Breve descrição do post (máx. 150 caracteres)', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marque para exibir o post publicamente'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', help_text='Selecione as tags relacionadas ao post', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Título do post (máx. 65 caracteres)', max_length=65),
        ),
    ]
